### ISSUE TITLE
Can't wild shape token that has had changes reverted

### ISSUE THREAD

**Issue by evandixon** [websterguy/pf1-mighty-morphin-mod#32] opened 2023-09-02 21:52 UTC
Repro steps:
1. Create an actor
2. Use wild shape macro or mighty morphin menu macro
3. Revert changes using the macro or by removing the wild shape buff
4. Use wild shape macro or mighty morphin menu macro again
5. Get an error about how the actor is already under the effect from step 2

Using Foundry 11 Stable Build 308 and Mighty Morphin 0.5.1.0

**Comment by websterguy** [comment] 2023-09-03 19:19
Cannot reproduce at all,
Is there a specific shape that is an issue?
Are there any errors in the console (F12, console tab) when you perform step 3?

**Comment by evandixon** [comment] 2023-09-03 20:55
Seems to be all effects that change form (beast shape, plant shape, elemental shape, wild shape), using the wild shape and overall mighty morphin menu

Scenario 1
- Clone an existing actor that hasn't had Mighty Morphin used on it
- Place the actor on a map and select it
- Wild Shape -> Execute Macro -> Animal -> Animal, Large, Dire Tiger -> OK
- Wild Shape -> Execute Macro -> Revert Changes -> OK
- Wild Shape -> Execute Macro -> Animal -> error ("Druid Melee (copy) is already under the effects of a change from Wild Shape)
- Delete the actor on the board and actor list so I can retry with other things.

Console output from scenario 1 (screen size error is when I opened the console):
![image](https://github.com/websterguy/pf1-mighty-morphin-mod/assets/2699524/5dc30017-5381-4d53-be14-d24c62b2b451)

Scenario 2
- Clone an existing actor that hasn't had MIghty Morphin used on it
- Place the actor on a map and select it
- Mighty Morphin Menu -> Execute Macro -> Beast Shape 2 -> Animal, Large, Dire Tiger -> OK
- Mighty Morphin Menu -> Execute Macro -> Revert Changes -> OK
- Mighty Morphin Menu -> Execute Macro -> Beast Shape 1 -> error ("Druid Melee (copy) is already under the effects of a change from Wild Shape)
- Delete the actor on the board and actor list so I can retry with other things.
Console output from scenario 2:
![image](https://github.com/websterguy/pf1-mighty-morphin-mod/assets/2699524/d440d737-a2dc-490a-88b1-18959b5ab1c5)

Other things that work (can revert changes then apply other changes, repeatedly; buff remains on buffs list but is marked inactive):
- Mighty Morphin -> Enlarge Person
- Mighty Morphin -> Frightful Aspect

Other things that don't work (it works getting into the form, reverting undoes buffs, but no further morphin macros work):
- Mighty Morphin -> Elemental Body 1/2
- Mighty Morphin -> Plant Shape 1

After typing this up I realized I had these modules enabled. I disabled them all except PF1 Might Morphin mod, reloaded the page, repeated scenario 1 with a Tiny Owl, and the issue persists.
![image](https://github.com/websterguy/pf1-mighty-morphin-mod/assets/2699524/d8e7e069-5847-4d3e-a9c3-764e00c2bd68)

**Comment by websterguy** [comment] 2023-12-27 06:21
Duplicate of #28 , unlinked tokens are issues

**Closed by websterguy** 2023-12-27 06:21 UTC
